# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet publish --configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)
  displayName: 'dotnet publish $(buildConfiguration)'
- task: file-creator@5
  inputs:
    fileoverwrite: true
    filepath: 'testdocker/appsettings.secret.json'
    filecontent: '{}'
    endWithNewLine: true
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'testdocker'
- task: CopyFiles@2
  displayName: 'copy deploy artifact'
  inputs:
    SourceFolder: 'Deploy'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: testdocker-deploy'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'testdocker-deploy'
